# -*- coding: utf-8 -*-
"""assignment_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

# Finger Exercise Lecture 11
# Implement the function that meets the specifications below:
# def remove_and_sort(Lin, k):
#     """ Lin is a list of ints
#         k is an int >= 0
#     Mutates Lin to remove the first k elements in Lin and
#     then sorts the remaining elements in ascending order.
#     If you run out of items to remove, Lin is mutated to an empty list.
#     Does not return anything.
#     """
#     # Your code here

# # Examples:
# L = [1,6,3]
# k = 1
# remove_and_sort(L, k)
# print(L)   # prints the list [3, 6]
def removeandsort(Lin, k):
    del Lin[:k]
    Lin.sort()

L = [1, 6, 3]
k = 1
removeandsort(L, k)
print(L)

L = [5, 2, 8, 1, 9]
k = 3
removeandsort(L, k)
print(L)

L = [10, 20, 30]
k = 5
removeandsort(L, k)
print(L)