# -*- coding: utf-8 -*-
"""assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

# Quiz s Interactive QsA
# • Quiz Topics Include:
        # o Definitions and importance of debugging
        # o Differences between syntax, runtime, logic, operator precedence, variable
        # binding, and type errors
        # o How print statements and IDE debuggers aid in the debugging process
# • Sample Questions:
# o What is a common cause of syntax errors in Python?
      # a) Incorrect use of operators
      # b) Missing colons or mismatched parentheses
      # c) Logic errors
      # d) None of the above
      # (ans=b)
# o How does operator precedence affect calculations?
      # a) It determines the order operations are performed
      # b) It affects variable binding
      # c) It only matters in loops
      # d) Itis irrelevant
      # (ans=c)
# o Which debugging technique can help you verify the state of variables
# mid-execution?
      # a) Using print statements
      # b) Rewriting the code entirely
      # c) Ignoring error messages
      # d) None of the above
      # (ans=c)