# -*- coding: utf-8 -*-
"""assignment_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

def subtract():
    """
    A function that subtracts two numbers entered by the user.
    Handles potential input errors gracefully.
    """
    try:
        a = int(input("Enter A: "))
        b = int(input("Enter B: "))
        print("Result:", a - b)
    except ValueError:
        print("Error: Please enter valid integers!")

# Test the function
if __name__ == "__main__":
    print("test:")
    subtract()

