# -*- coding: utf-8 -*-
"""assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

#frequency counter program
#ask for user input
num_str=input("Enter a positive integer:")
# validate the users input
if num_str.isdigit():

    #initialize a dictionary
    counts={}

    #iterate over each character in the string
    for ch in num_str:
        #populate the dictionary with frequency of values inside the string
        counts[ch]=counts.get(ch,0)+1

    #iterate through the dictionary to display the frequency for each value
    for dg in sorted(counts):
        print(f"Digits{dg}:{counts[dg]}")

# 🎯 Welcome to the Guess the Number Game!
# I'm thinking of a number between 1 and 50.
# You have 5 attempts to guess it. Good luck!

# Attempt 1/5: Enter your guess (1-50): 35
# 🔥 Way too high! Try a much lower number.

# Attempt 2/5: Enter your guess (1-50): 12
# 📈 Too low! Try a slightly higher number.

# Attempt 3/5: Enter your guess (1-50): 45
# 🔥 Way too high! Try a much lower number.

# Attempt 4/5: Enter your guess (1-50): 13
# 📈 Too low! Try a slightly higher number.

# Attempt 5/5: Enter your guess (1-50): 26
# 🔥 Way too high! Try a much lower number.

# 💔 Game over! You've used all 5 attempts.
# The secret number was: 15

# Would you like to play again? (yes/no): yes

# ========================================
# 🎯 Welcome to the Guess the Number Game!
# I'm thinking of a number between 1 and 50.
# You have 5 attempts to guess it. Good luck!

# Attempt 1/5: Enter your guess (1-50): 23
# 📈 Too low! Try a slightly higher number.

# Attempt 2/5: Enter your guess (1-50): 43
# 🔥 Way too high! Try a much lower number.

# Attempt 3/5: Enter your guess (1-50): 21
# 📈 Too low! Try a slightly higher number.

# Attempt 4/5: Enter your guess (1-50): 33
# 📉 Too high! Try a slightly lower number.

# Attempt 5/5: Enter your guess (1-50): 20
# 📈 Too low! Try a slightly higher number.

# 💔 Game over! You've used all 5 attempts.
# The secret number was: 30

# Would you like to play again? (yes/no): no
# Thanks for playing! 👋

# ==================================================
# Import the built in random module.
# Generate a random integer between 1 and 50:
import random
secret=random.randint(1,5)

#Set a counter attempts = 0 and a maximum max_attempts = 5.
attempts=0
max_attempts=5

#implement a while loop to allow up to 5 guesses
#prompt the user for an attempt
while attempts < max_attempts:
    guess=int(input(f"Attempt {attempts+1}/{max_attempts}:Your guess?"))

    # Increment attempts += 1.
    attempts+=1

    #use branching to check if guess is less than,greater than or equall to and print some statements
    if guess == secret:
        print(f"Correct! You guessed the number in {attempts} tries")
        break
    elif guess < secret:
        print("Too low! Try again")
    else:
        print("Too high! Try again.")

#if the max_number of attempts is reached print the secret number
else:
    print(f"out of attempts. the number was: {secret}")