# -*- coding: utf-8 -*-
"""assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

# Below is an intentionally buggy version of the program. Notice that the calculation of the perimeter is incorrect.
# Run this code, observe its output, discuss why the result is wrong, and identify what needs to be fixed.
# Buggy version: Calculate rectangle metrics with an incorrect perimeter calculation
# Modify the buggy version to apply the correct formula.
# Re-run the code to verify that the corrected version prints the expected perimeter (22.0 in this example).



# Define the dimensions of the rectangle

length = 8.0       # Length of the rectangle (in units)
width = 3.0        # Width of the rectangle (in units)

# Calculate the area of the rectangle correctly
area = length * width

# Bug: Incorrect perimeter calculation
# Intended formula: 2 * (length + width)
# Buggy formula here misses one full width value
perimeter = (length * 2) + width

# Print the results
print("Area:", area)
print("Perimeter (buggy):", perimeter)

# initialize the dimensions of the rectangle

length = 8.0       # Length of the rectangle (in units)
width = 3.0        # Width of the rectangle (in units)

# formulae for calculating area of the rectangle
area = length * width

# formulae for calculating perimeter of the rectangle
perimeter = 2*(length + width)

# Print the results for both area and perimeter simultaniously using f strings function to print
print(f"Area:{area}")
print(f"Perimeter (buggy): {perimeter}")