# -*- coding: utf-8 -*-
"""assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtfOcI_Zh3VhcFmRMXtVxjQ_byv8x8B
"""

### **Assignment Instructions:**
# 1. **Refactor the Code:**
    #- **Improve Formatting:**
        #- Separate multiple statements onto individual lines.
        #- Ensure proper spacing around operators.
    #- **Use Meaningful Variable Names:**
        #- Rename variables like `r`, `h`, `vol`, and `sa` to more descriptive names (e.g., `radius`, `height`, `volume`, `surface_area`).
    #- **Add Comments:**
        #- Include comments that explain each part of the code (e.g., what the formulas compute).
    #- **Enhance Readability:**
        #- Structure the code in a way that it is easy to read and understand.
#2. **Test Your Code:**
    #- Run the refactored code to verify that it correctly computes and prints the cylinder’s volume and surface area.
    #- Ensure that the functionality remains unchanged.


# # messy code to compute cylinder metrics
# r=3.0; h=5
# vol=3.14159*r**2*h; sa=2*3.14159*r*(r+h)
# print("Vol:",vol,"SurfArea:", sa)


#initialize values for radius and height
radius=3.0
height=5.0

#formulae to calculate volume
volume=3.14159*radius**2*height

#formulae to calculate surface area
surface_area=2*3.14159*radius*(radius+height)

#print the volume and surface area using f strings function
print(f"Volume:{volume}")
print(f"Surface Area:{surface_area}")