# -*- coding: utf-8 -*-
"""Assignment 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzwzQMPtsWkFkdlaXk3IkEkij9-4vxrB
"""

#Fix the bug:
# def subtract():
#     a = input("Enter number: ")
#     b = input("Enter number: ")
#     print("Result:", a - b)

#Fix the bug and use int() conversion
def subtract():
    a = int(input("Enter number: "))
    b = int(input("Enter number: "))
    print("Result:", a - b)

subtract()

# Add assert to This Code:

# def check_age(age):
#     # add assertion here
#     print("Age is okay.")
def check_age(age):
    assert age >= 0, "Age cannot be negative."
    print("Age is okay.")

check_age(25)

# Use raise to catch invalid input:

# def is_even(n):
#     # if n is not an int, raise Exception
#     return n % 2 == 0

def is_even(n):
    if not isinstance(n, int):
        raise Exception("Input must be an integer.")
    return n % 2 == 0

print(is_even(4))
print(is_even(5))