# -*- coding: utf-8 -*-
"""ASSIGNMENT 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uJsC3FSScHz5RCcduL4qSo093lR2QiA
"""

#1.
#Write a program that:
#Takes a list of names
#Removes duplicates
#Sorts alphabetically

def clean_names(name_list):
    # Remove duplicates using set, then convert back to list
    unique_names = list(set(name_list))
    # Sort alphabetically
    unique_names.sort()
    return unique_names

names = ["Alice", "John", "Bob", "Alice", "Eve", "John"]
result = clean_names(names)
print("Cleaned List:", result)

#2.What happens in this code?
# Python Code :

# L1 = ['sun']
# L2 = L1
# L1 = ['moon']
# print(L2)
L1 = ['sun']
L2 = L1
L1 = ['moon']
print(L2)

# 3. Practice
# Create a list of 10 names.
# Remove duplicates.
# Sort alphabetically.
# Print the result.

names = ["Liam", "Noah", "Olivia", "Emma", "Ava", "Liam", "Sophia", "Noah", "Isabella", "Mia"]
unique_names = list(set(names))
unique_names.sort()

print("Sorted Unique Names:", unique_names)