# -*- coding: utf-8 -*-
"""Final Exercise Lecture 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dde2RC0p9knI2TOGItyq3vbf0Vnwy3FW
"""

def remove_and_sort(Lin, k):
    """ Lin is a list of ints
        k is an int >= 0
    Mutates Lin to remove the first k elements in Lin and
    then sorts the remaining elements in ascending order.
    If you run out of items to remove, Lin is mutated to an empty list.
    Does not return anything.
    """
    del Lin[:k] #removes the first elements from the list
    Lin.sort() #sorts the remaining elements in place


L = [1,6,3]
k = 1
remove_and_sort(L, k)
print(L)