# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPiw92KSdHq-U82tcko-NgFcpI6AdVn0
"""

#import the biuld in random module
#Generate a random integer between 1-50:
import random
secret = random.randint(1,50)
attempts = 0
max_attempts = 5
#Use a while loop(while attempts<max attempts:)to allow upto 5 guesses:
while attempts < max_attempts:
  guess = int(input(f"Attempt{attempts+1}/{max_attempts}: Your guess?"))
  #Increment the number of attempts
  attempts += 1
  if guess == secret:
    print("Correct! You guessed the numnber in", attempts, "tries")
    break
  elif guess < secret:
    print("Too low! Try again.")
  else:
    print("Too high! Try again.")
#After the loop, if the user didn't guess correctly:
else:
  print("Out of attempts. The number was", secret)