# -*- coding: utf-8 -*-
"""StudentProfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLZP-jGoNonggqgl3vYrC1PPLapfUTGU
"""

# Simple Project to Create A Student Profile
# Define the Variables
Full_name = str(input("Enter Your Name: "))
Age = int(input("Enter Your Current Age: "))
Height = float(input("Enter Your Height in Centimeters: "))
Student = True
# Display of Input from the Student
print("Personal Profile")
print(f"FULL NAMES: {Full_name}.")
print(f"AGE: {Age} years.")
print(f"HEIGHT: {Height}cm.")
print(f"Student Status:{Student} ")

