# -*- coding: utf-8 -*-
"""TeddyAssDigCount.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpLjMfxPkATPH1vxfCL8lias-AXamLiR
"""

# User to enter the Digits
num_str = input("Enter a positive integer: ")

# Create a dictionary to store digit counts
digits_count = {}

# Check for user input digits and count the digits
for digits in num_str:
  try:
    if digits.isdigit():
        digits_count[digits] = digits_count.get(digits, 0) + 1
  except ValueError:
    print("Invalid input. Please enter a positive integer.")

# Sort the digits and print each digit
for digits in sorted(digits_count):
    print(f"Digit {digits}: {digits_count[digits]} time(s)")