# -*- coding: utf-8 -*-
"""TeddyAss8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjtENMxvUXA8d7tgjnKqR7KgHZ70AqUe
"""

def average(Ln):
    total = sum(Ln)
    cnt = len(Ln)
    avg = total / cnt
    return avg

mylist = [4, 8, 10, 6]
print("Average is:", average(mylist))

def total_wds(words):
    total = 0
    for w in words:
        total += len(w)
    return total
my_list = ["Science", "Cyber", "Database"]
print("Total letters:", total_wds(my_list))

numb = [7, 11, 12, 16, 18]

# Filter with lambda to GET numbers div3
division3 = filter(lambda number: number % 3 == 0, numb)

# Convert & print it
print("Numbers divisible by 3:", list(division3))

def dot_product(tA, tB):
    """
    tA: a tuple of numbers
    tB: a tuple of numbers of the same length as tA
    Returns a tuple (length, dot product of tA and tB)
    """
    total = 0
    for i in range(len(tA)):
        total += tA[i] * tB[i]
    return (len(tA), total)

# Example:
print(dot_product((1, 2, 3), (4, 5, 6)))  # ➜ (3, 32)
print(dot_product((5, 2, 6, 4), (3, 2, 4, 3)))

