# -*- coding: utf-8 -*-
"""TeddyAss11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEf1w0YVi6fHaBx9MKbJUU-BnZP7SzG0
"""

def remove_and_sort(Lin, k):
    # Remove the first k elements (handle case if k > len(Lin))
    del Lin[:k]
    #Sort the remaining elements
    Lin.sort()

L = [1, 6, 3]
k = 1
remove_and_sort(L, k)
print(L)