# -*- coding: utf-8 -*-
"""TeddyAssGuessNum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16j9qylelACD4hd7z_1pdyBDnRqCOdaTj
"""

import random

# Generate a random number between 1 and 50
secret = random.randint(1, 50)

# Initialize attempt counter and max attempts
attempts = 0
max_attempts = 5

# Guessing loop
while attempts < max_attempts:
    guess = int(input(f"Attempt {attempts + 1}/{max_attempts}: Your guess? "))
    attempts += 1

    if guess == secret:
        print("Correct! You guessed the number in", attempts, "tries.")
        break
    elif guess < secret:
        print("Too low! Try again.")
    else:
        print("Too high! Try again.")

# If not guessed within max attempts
else:
    print("Out of attempts. The number was ", secret)