# -*- coding: utf-8 -*-
"""TemperatureConverter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LiNrH0Zu6aITl6sm5SEGEJAOGpVh5NRI
"""

# Program to Convert Temperature from Celsius to Fahrenheit
# User input
celsius_input = input("Enter Temperature in Celsius: ")
# Convert the input to a Float Value
celsius = float(celsius_input)
# Convert Temperature from Celsius to Fahrenheit
fahrenheit = ( celsius * 9/5) + 32
print("Temperature in Fahrenheit: ", fahrenheit)
# Printing Conditions
if celsius <= 0:
    print("It's Freezing Cold")
elif 1 <= celsius < 20:
    print("It's Chilly ")
elif 21 <= celsius < 30:
    print("It's Warm Outside")
else:
    print("It's too Hot")

