# -*- coding: utf-8 -*-
"""Assignment_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcxeEGw261-LlEYEIYYDbhE1EUst3jTP
"""

def keep_consonants(word):
    vowels = "aeiouAEIOU"
    result = ""
    for char in word:
        if char.isalpha() and char not in vowels:
            result += char
    return result

# 🧪 Example
print(keep_consonants("babas"))     # Output: bbs
print(keep_consonants("Hello"))     # Output: Hll
print(keep_consonants("PYTHON!"))   # Output: PYTHN

def keep_consonants_from_input():
    word = input("Enter a word: ")
    return keep_consonants(word)

print(keep_consonants_from_input())

