# -*- coding: utf-8 -*-
"""Assignment13&14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SA7nv2EKIWjiLFHtmSwjOPsO3GvPtTSL
"""

#Q1. Implement the function that meets the specification below:
def safe_average(L):
    """
    L is a list of numbers (ints or floats). It may be empty or contain non-numeric values.

    Returns the average of all valid numeric elements in the list.

    - Ignores non-numeric items using exception handling.
    - If there are no numeric elements, raises a ValueError.
    """
    total = 0
    count = 0

    for item in L:
        try:
            # Attempt to convert to float (works for both int and float)
            number = float(item)
            total += number
            count += 1
        except (ValueError, TypeError):
            continue  # Skip non-numeric items

    if count == 0:
        raise ValueError("No numeric elements in the list.")

    return total / count

# Examples:
print(safe_average([10, 20, "thirty", 40]))  # prints 23.333...
print(safe_average(["a", "b"]))              # raises ValueError

#Q2. Implement the function that meets the specification below:
def validate_transaction(amounts):
    """
    amounts is a non-empty list of positive integers or floats representing transaction values.

    Uses assertions to ensure:
    - the list is not empty
    - all amounts are positive
    Returns the total amount.

    Raises AssertionError with a message if validations fail.
    """
    assert len(amounts) > 0, "Transaction list is empty"

    for amount in amounts:
        assert isinstance(amount, (int, float)) and amount > 0, "Transaction amount must be positive"

    return sum(amounts)

# Examples:
print(validate_transaction([100, 250.5, 89]))   # prints 439.5
print(validate_transaction([]))                # raises AssertionError: "Transaction list is empty"
print(validate_transaction([100, -50]))        # raises AssertionError: "Transaction amount must be positive"

#Q3. Implement the function that meets the specification below:
def student_score_summary(scores, threshold):
    """
    scores: a dictionary mapping student names (str) to total scores (int).
    threshold: an integer score threshold.

    Returns a list of student names who scored above the threshold.
    The list should be sorted alphabetically.
    """
    # Filter students who scored above the threshold
    qualified_students = [name for name, score in scores.items() if score > threshold]

    # Sort the list alphabetically
    qualified_students.sort()

    return qualified_students

# Examples:
students = {"Alice": 85, "Bob": 92, "Charlie": 78, "Daisy": 95}
print(student_score_summary(students, 80))   # prints ['Alice', 'Bob', 'Daisy']
print(student_score_summary(students, 100))  # prints []

#Q4. Implement the function that meets the specification below:
def merge_inventory(inv1, inv2):
    """
    inv1 and inv2 are dictionaries mapping item names (str) to quantities (int).

    Returns a new dictionary that combines both inventories.
    If an item appears in both, their quantities are summed.
    """
    merged = inv1.copy()  # Start with a copy of inv1 to avoid modifying it

    for item, quantity in inv2.items():
        if item in merged:
            merged[item] += quantity  # Sum quantities if item exists
        else:
            merged[item] = quantity   # Add new item

    return merged

# Examples:
inv1 = {"pen": 10, "notebook": 5}
inv2 = {"notebook": 3, "eraser": 7}
print(merge_inventory(inv1, inv2))  # prints {'pen': 10, 'notebook': 8, 'eraser': 7}
