# -*- coding: utf-8 -*-
"""Assignment12Elsa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbO9-Qlg1Liw8c3IfLyvjRcSW4FkPv2Q
"""

def subtract():
    a = int(input("Enter number: "))
    b = int(input("Enter number: "))
    print("Result:", a - b)
print(subtract())

#Add assert to this code
def check_age(age):
    assert age > 0
    print("Age is okay.")
check_age(9)

#Use raise to catch invalid input:
def is_even(n):
    # if n is not an int, raise Exception
    try:
     return n % 2 == 0
    except NameError:
      return "Please enter a number"
print(is_even(7))

