# -*- coding: utf-8 -*-
"""Assignment 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZcUoKeeq_HHGPr6PJ9jAmwBN8kSNiJi
"""

#  Box Class
class Box:
    def __init__(self, length, width, height):
        self.length = length
        self.width = width
        self.height = height

    def get_volume(self):
        return self.length * self.width * self.height

    def is_cube(self):
        return self.length == self.width == self.height

    def bigger(self, other):
        return self if self.get_volume() > other.get_volume() else other


#  Song Class
class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration  # in seconds

    def is_long(self):
        return self.duration > 300

    def same_artist(self, other):
        return self.artist == other.artist

    def longer_song(self, other):
        return self if self.duration > other.duration else other


#  Example usage
if __name__ == "__main__":
    # Box examples
    box1 = Box(3, 3, 3)
    box2 = Box(4, 2, 2)

    print("Box 1 volume:", box1.get_volume())        # 27
    print("Box 2 volume:", box2.get_volume())        # 16
    print("Box 1 is cube:", box1.is_cube())          # True
    print("Box 2 is cube:", box2.is_cube())          # False
    print("Bigger box volume:", box1.bigger(box2).get_volume())  # 27

    print("\n---\n")

    # Song examples
    song1 = Song("Everlong", "Foo Fighters", 250)
    song2 = Song("November Rain", "Guns N' Roses", 540)

    print("Song 1 is long:", song1.is_long())        # False
    print("Song 2 is long:", song2.is_long())        # True
    print("Same artist:", song1.same_artist(song2))  # False
    print("Longer song:", song1.longer_song(song2).title)  # November Rain