# -*- coding: utf-8 -*-
"""Temprature Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bxjs8LZKllrXH4arUK7QNaxkdsXH-n8E
"""

# Converting temprature  for celcius to fahrenheit
#Users point
celsius_input= input("Enter Temprature in Celcius")
#Convert the input to a float value
celcius= float(celsius_input)
#Convert Temprature from celcius to fahrenheit
fahrenhiet = (celcius * 9/5) + 32
print("Temprature in fahrenhiet :",fahrenheit)

if celcius <=0:
  print("its freezing cold")
elif  1 <= celcius <=  20:
  print("its chilly")
elif  21 <= celcius <=  30:
  print("its warm outside")
else:
  print("its too hot")

#Defining Variables
full_name=input("Enter your full name:")
age=int(input("Enter your age:"))
height=float(input("Enter your height:"))
student=True

#Results
print(f"full name:" ,{full_name})
print(f"age:" ,{age})
print(f"enter you {height}:" ,)
print(f" {student}:")