# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159Gnrzaob4Tp6DTRqgdStnJ1yc0wjMWq
"""

# Converting temprature  for celcius to fahrenheit
#Users point
celsius_input= input("Enter Temprature in Celcius")
#Convert the input to a float value
celsius= float(celsius_input)
#Convert Temprature from celcius to fahrenheit
fahrenheit = (celcius * 9/5) + 32
print("Temprature in fahrenhiet :",fahrenheit)

if celsius <=0:
  print("its freezing cold")
elif  1 <= celsius <=  20:
  print("its chilly")
elif  21 <= celsius <=  30:
  print("its warm outside")
else:
  print("its too hot")