# -*- coding: utf-8 -*-
"""Teddy_Midterm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UGCvK840GAngJbFGLHCdGCfiJQ5CJqB
"""

# 11. GRADE CONVERTER
# Get the exam score between 0 to 100 from the user
try:
 score = int(input("Enter the exam score between 0 and 100: "))
# Check the entered score to output the corresponding letter Grade
 if 90 <= score <= 100:
    print("Grade: A")
 elif 80 <= score < 90:
    print("Grade: B")
 elif 70 <= score < 80:
    print("Grade: C")
 elif 60 <= score < 70:
    print("Grade: D")
 elif 0 <= score < 60:
    print("Grade: F")
 else:
    print("Invalid Input. Please enter the Grade between 0 and 100!")
except ValueError:
  print("Invalid Input. Please enter a number. ")

# 12. VOWEL COUNTER
# Initialise the number of vowel count to zero
vowel_count = 0
# Get the sentence input from the user
sentence = input("Enter a sentence: ")
# Loop over each character in the sentence and check for any vowel either upper or lower
for char in sentence:
  if char in "aeiouAEIOU":
    vowel_count += 1
# Output the results
print("Total number of vowels: ", vowel_count)

# 13. Decimal to Binary Converter
# Get a positive number from the user
numb = int(input("Enter a positive integer: "))
# Store the entered number in a list
result = ""

if numb == 0:
  result = "0"
else:
# Convert the positive number to binary
  while numb > 0:
    binary = numb % 2
    result = str(binary) + result
    numb //= 2
# Output the results
print("Binary: ", result)

# 14. SUM OF DIGITS
# Initialize the sum of digits to zero
sum_of_digits = 0
#  Get a positive number from the user
number = int(input("Enter a positive integer: "))
# Compute the sum of each digit
while number > 0:
  digit = number % 10
  sum_of_digits += digit
  number //= 10
# Output the results
print("Sum of digits: ", sum_of_digits)