# -*- coding: utf-8 -*-
"""assigmjent 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5ZDC3a0qJjUMj394CxgmXZtJqIfS5xj
"""

#create a function that;
#Asks the user for a word
#Returns only the consonants from that word
def keep_consonants():
    word = input("Enter a word: ")
    vowels = "aeiouAEIOU"
    result = ""
    for char in word:
        if char.isalpha() and char not in vowels:
            result += char
    return result

print(keep_consonants())

