# -*- coding: utf-8 -*-
"""Asiignment_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYZY_No_UoiEnoJGInm5b_ShQCn6I5fb
"""

L1 = ['sun']
L2 = L1
L1 = ['moon']
print(L2)

# Step 1: Create a list with some duplicate names
names = ["Alice", "Bob", "Charlie", "Alice", "Eve", "Frank", "Diana", "Bob", "Grace", "Hank"]

# Step 2: Remove duplicates using set()
unique_names = list(set(names))

# Step 3: Sort alphabetically
unique_names.sort()

# Step 4: Print result
print(unique_names)

