# -*- coding: utf-8 -*-
"""assignment_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qF5XcYTJ08IAEcnPuKd_DZUry9kZ1qbX
"""

class Book:
    def __init__(self, title, author, year, copies_available):
        self.title = title
        self.author = author
        self.year = year
        self.copies_available = copies_available

    def borrow(self):
        if self.copies_available > 0:
            self.copies_available -= 1
        else:
            print("Not available.")

    def return_book(self):
        self.copies_available += 1

    def is_same_book(self, other):
        return self.title == other.title and self.author == other.author

    def __str__(self):
        return f"{self.title} by {self.author} ({self.year}) - Copies: {self.copies_available}"

b1 = Book("Python Basics", "Dennis Omboga", 2024, 3)
b2 = Book("Python Basics", "Dennis Omboga", 2024, 2)

b1.borrow()          # 3 → 2
b1.borrow()          # 2 → 1
b1.return_book()     # 1 → 2

print(b1.copies_available)   # Output: 2
print(b1.is_same_book(b2))   # Output: True

print(b1)
print(b2)
print(b1.is_same_book(b2))

from math import gcd

class Fraction:
    def __init__(self, num, denom):
        if denom == 0:
            raise ValueError("Denominator cannot be zero.")
        self.num = num
        self.denom = denom
        self.simplify()

    def simplify(self):
        common = gcd(self.num, self.denom)
        self.num //= common
        self.denom //= common
        # Ensure denominator is positive
        if self.denom < 0:
            self.num *= -1
            self.denom *= -1

    def __add__(self, other):
        new_num = self.num * other.denom + other.num * self.denom
        new_denom = self.denom * other.denom
        return Fraction(new_num, new_denom)

    def __eq__(self, other):
        return self.num * other.denom == self.denom * other.num

    def __str__(self):
        return f"{self.num}/{self.denom}"

f1 = Fraction(1, 2)
f2 = Fraction(1, 4)
f3 = f1 + f2

print(f3)                      # Output: 3/4 (simplified from 6/8)
print(f1 == f2)                # Output: False
print(f1 == Fraction(2, 4))    # Output: True

