# -*- coding: utf-8 -*-
"""Assignment_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoKeVyRplXkznmBpCy4YN1TlK-glrTFH
"""

def greet(name, message="Hello"):
    print(f"{message}, {name}!")

# Calls
greet("Alice")            # Output: Hello, Alice!
greet("Bob", "Welcome")   # Output: Welcome, Bob!

def profile(name, age, city):
    print(f"{name} is {age} years old and lives in {city}.")

# Calls
profile("Jane", 25, "Nairobi")
profile(age=30, city="Kisumu", name="Peter")  # Using keyword args

squares = []
for i in range(5):
    squares.append(i * i)
print(squares)  # [0, 1, 4, 9, 16]

squares = [i * i for i in range(5)]
print(squares)

# Original (buggy)
#def add(x, y)
    #return x + y

# Fixed
def add(x, y):
    return x + y

# Original (buggy)
names = ["Ali", "Asha", "Bob"]
#print(names[3])  # IndexError

# Fixed
print(names[2])  # or use len(names) to avoid going out of range

# Original (buggy)
def multiply(a, b=2):
    return a * b

#print(multiply())  # TypeError

# Fixed
print(multiply(3))  # Works now, b has default value

