# -*- coding: utf-8 -*-
"""assignment_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAjdzReuRPvL3UhCXy3_7wjZj8OLqHh0
"""

class Box:
    def __init__(self, length, width, height):
        self.length = length
        self.width = width
        self.height = height

    def get_volume(self):
        return self.length * self.width * self.height

    def is_cube(self):
        return self.length == self.width == self.height

    def bigger(self, other):
        if self.get_volume() >= other.get_volume():
            return self
        else:
            return other

box1 = Box(3, 3, 3)
box2 = Box(2, 4, 5)

print(box1.get_volume())
print(box1.is_cube())
print(box2.is_cube())

class Song:
    def __init__(self, title, artist, duration):
        self.title = title
        self.artist = artist
        self.duration = duration  # in seconds

    def is_long(self):
        return self.duration > 300

    def same_artist(self, other):
        return self.artist == other.artist

    def longer_song(self, other):
        if self.duration >= other.duration:
            return self
        else:
            return other

song1 = Song("Imagine", "John Lennon", 183)
song2 = Song("Hey Jude", "The Beatles", 431)

print(song1.is_long())
print(song2.is_long())
print(song1.same_artist(song2))

