# -*- coding: utf-8 -*-
"""BinaryTeddyTag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vwP6clfgl8yI-ZURpMQA6Nv2UYrVLc9
"""

# User to enter their first name
name = input("Enter your first name: ")

# Loop through each character
print("\nCode Output:")
print(f"Your Name: {name.upper()}")

for char in name.upper():
# Convert to ASCII
    ascii_value = ord(char)
# Convert ASCII to binary
    binary_value = format(ascii_value, '08b')
# Print the output
    print(f"{char} → {ascii_value} → {binary_value}")

# Store hidden value which is 11 in decimal
secret_binary = '1011'

print(f"Guess the number that matches the secret binary code: {secret_binary}")

# Loop until the user guesses the correct number
while True:
    try:
        guess = int(input("Your guess: "))
# Convert guess to binary
        guess_binary = format(guess, 'b')

        print(f"Binary of {guess} is {guess_binary}", end=" -- ")

        if guess_binary == secret_binary:
            print("Door Unlocked!")
            break
        else:
            print("It is not a match.\n")
    except ValueError:
        print("Please enter a valid integer.\n")