# -*- coding: utf-8 -*-
"""Assignment_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYK9Qpkdur79-eljH79YElBNCA8GbY3x
"""

def remove_and_sort(Lin, k):
    """
    Lin is a list of ints.
    k is an int >= 0.
    Mutates Lin to remove the first k elements in Lin and
    then sorts the remaining elements in ascending order.
    If you run out of items to remove, Lin is mutated to an empty list.
    Does not return anything.
    """
    # Step 1: Remove the first k elements (handle case if k > len(Lin))
    del Lin[:k]

    # Step 2: Sort the remaining elements
    Lin.sort()

L = [1, 6, 3]
k = 1
remove_and_sort(L, k)
print(L)   # Output: [3, 6]

