# -*- coding: utf-8 -*-
"""Lamech_MidtermExam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-P6FECPd5yuzclcJAchDbo-SB9h7E1H
"""

# 11. Grade Converter(8 marks)
#Asks the user for an exam score
try:
    score = int(input("Enter exam score (0-100): "))#Asks for user's exam score

#Score range(integer 0-100)

    if 0 <= score <= 100:
        if 90 <= score <= 100:
            print("Grade: A")
        elif 80 <= score <= 89:
            print("Grade: B")
        elif 70 <= score <= 79:
            print("Grade: C")
        elif 60 <= score <= 69:
            print("Grade: D")
        else: # 0-59
            print("Grade: F")
    else:
        print("Invalid score. Please enter a score between 0 and 100.")
except ValueError:
    print("Invalid input. Please enter an integer score.")

# 12: Vowel Counter(7 marks)
#Ask the user to enter a sentence (string)

sentence = input("Enter a sentence: ")
vowel_count = 0
vowels = "aeiou"

for char in sentence:
    if char.lower() in vowels:
        vowel_count += 1

print(f"Total number of vowels: {vowel_count}")

# Decimal to binary Counter(8 marks)
#Asks the user for non-negative integer and prrints its binary representation as a strig of 0 and 1

try:
    decimal_num = int(input("Enter a non-negative integer: "))

    if decimal_num < 0:
        print("Please enter a non-negative integer.")

    else:
        binary_representation = ""
        temp_num = decimal_num
        while temp_num > 0:
            remainder = temp_num % 2
            binary_representation = str(remainder) + binary_representation
            temp_num //= 2
        print(f"Binary representation: {binary_representation}")
except ValueError:
    print("Invalid input. Please enter an integer.")

# 14. Sum of Digits(7 marks)
#Ask the user to enter a positive integer

try:
    num_str = input("Enter a positive integer: ")


    if not num_str.isdigit() or int(num_str) <= 0:
        print("Invalid input. Please enter a positive integer.")

    else:
        sum_of_digits = 0
        for digit_char in num_str:
            sum_of_digits += int(digit_char)
        print(f"Sum of digits: {sum_of_digits}")
except ValueError:
    print("Invalid input. Please enter an integer.")

